import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  private arabicNames: string[] = [
    'محمد', 'أحمد', 'علي', 'عمر', 'خالد', 'فاطمة', 'زينب', 'مريم', 'سارة', 'نور',
    'عبدالله', 'يوسف', 'حسن', 'حسين', 'إبراهيم', 'مصطفى', 'محمود', 'كريم', 'هدى', 'آية',
    'عبدالرحمن', 'سعيد', 'سلطان', 'فهد', 'فيصل', 'تركي', 'بدر', 'سلمان', 'منصور', 'نواف',
    'مها', 'ريم', 'شهد', 'حنان', 'إيمان', 'أمل', 'منى', 'نورة', 'جود', 'لمى',
    'طارق', 'زياد', 'ياسر', 'سامي', 'هشام', 'ماجد', 'وليد', 'جمال', 'عادل', 'فؤاد',
    'خديجة', 'عائشة', 'رقية', 'صفية', 'أسماء', 'جواهر', 'لطيفة', 'علياء', 'شيماء', 'هند',
    'سعد', 'صالح', 'نايف', 'مشعل', 'ثامر', 'بندر', 'راشد', 'مبارك', 'جابر', 'ناصر',
    'غادة', 'عبير', 'أحلام', 'نجلاء', 'وفاء', 'سعاد', 'هناء', 'دلال', 'أروى', 'بشرى',
    'أسامة', 'أيمن', 'معاذ', 'بلال', 'عمار', 'صهيب', 'أنس', 'زيد', 'جعفر', 'حمزة',
    'ليلى', 'سلمى', 'نجوى', 'دينا', 'رنا', 'داليا', 'هالة', 'سناء', 'رجاء', 'فاتن',
    'فواز', 'غسان', 'مروان', 'بسام', 'حاتم', 'لؤي', 'وائل', 'رياض', 'عصام', 'جهاد',
    'ياسمين', 'سمر', 'نهى', 'رشا', 'غيداء', 'روان', 'لجين', 'وتين', 'تالا', 'يارا',
    'خليل', 'رشيد', 'نبيل', 'شريف', 'كمال', 'وفيق', 'عماد', 'بهاء', 'ضياء', 'زكريا',
    'مرام', 'وئام', 'أفنان', 'أشواق', 'تهاني', 'نوال', 'مي', 'هيا', 'أثير', 'رهف',
    'مازن', 'مهند', 'فراس', 'إياد', 'رائد', 'تامر', 'حازم', 'شاكر', 'عاصم', 'كامل',
    'رويدا', 'نسرين', 'شيرين', 'نرمين', 'جيهان', 'إلهام', 'حصة', 'منيرة', 'وضحى', 'العنود',
    'قصي', 'عدي', 'مؤيد', 'مصعب', 'صفوان', 'سهيل', 'غيث', 'ليث', 'كنان', 'ريان',
    'أريج', 'آلاء', 'إسراء', 'براءة', 'تقوى', 'جهان', 'حوراء', 'دعاء', 'ذكرى', 'رحمة',
    'رامي', 'فادي', 'هاني', 'شادي', 'نديم', 'وسيم', 'فادي', 'غالب', 'ظافر', 'عابد',
    'زهرة', 'سوسن', 'نرجس', 'وردة', 'أقحوان', 'بنفسج', 'توليب', 'ريحانة', 'خزامى', 'فلّة',
    'آدم', 'نوح', 'موسى', 'عيسى', 'هارون', 'داوود', 'سليمان', 'يعقوب', 'إسماعيل', 'إسحاق',
    'بلقيس', 'كليوباترا', 'زنوبيا', 'نفرتيتي', 'شجرة', 'الدر', 'زبيدة', 'أروى', 'الصباحي', 'قمر',
    'جاسم', 'حمد', 'راكان', 'سطام', 'طلال', 'عبدالعزيز', 'عبدالكريم', 'عبدالمجيد', 'عزام', 'فارس',
    'أنهار', 'أسرار', 'أصالة', 'اعتماد', 'أفراح', 'آمال', 'انتصار', 'إنصاف', 'ابتهال', 'ازدهار',
    'حاتم', 'حسام', 'حيدر', 'دريد', 'ذوالفقار', 'راجح', 'زاهر', 'ساجد', 'شاهر', 'صابر',
    'بسمة', 'بشاير', 'بهية', 'بيان', 'بيداء', 'تغريد', 'تحرير', 'تذكار', 'تسنيم', 'تمام',
    'عابد', 'عاطف', 'عباس', 'عثمان', 'عدنان', 'علاء', 'عرفان', 'عصمت', 'عكرمة', 'عمران',
    'ثريا', 'ثواب', 'جميلة', 'جنان', 'جنى', 'جوهرة', 'حبيبة', 'حسناء', 'حكمة', 'حليمة',
    'غانم', 'فايز', 'فريد', 'فلاح', 'فهمي', 'قاسم', 'قيس', 'كاظم', 'كرم', 'ماهر',
    'خاتون', 'خالدة', 'ختام', 'خلود', 'خميلة', 'دانية', 'دجى', 'درة', 'دعد', 'ديمة',
    'مأمون', 'مجاهد', 'مدحت', 'مراد', 'مشاري', 'مطيع', 'مروان', 'نادر', 'ناجي', 'ناظم',
    'ذكرى', 'ذهب', 'رائدة', 'رابحة', 'راتبة', 'راجية', 'راوية', 'رحاب', 'رحيق', 'رغد',
    'نذير', 'نزار', 'نعمان', 'نعيم', 'نمر', 'هادي', 'هاشم', 'همام', 'هيثم', 'واصل',
    'رزان', 'رشا', 'رضوى', 'رفيف', 'رندة', 'رهام', 'روعة', 'ريما', 'زكية', 'زمزم',
    'وافي', 'وحيد', 'وديع', 'وسام', 'يحيى', 'يعرب', 'يمان', 'ياسين', 'يزن', 'يونس',
    'زهور', 'زينة', 'سجى', 'سحر', 'سلوى', 'سماح', 'سمية', 'سندس', 'سهاد', 'سهام',
    'أشرف', 'أكرم', 'أمين', 'إحسان', 'باهر', 'بشير', 'توفيق', 'جلال', 'جاسر', 'حبيب',
    'شادية', 'شريفة', 'شمس', 'شوق', 'صابرين', 'صافية', 'صباح', 'صبا', 'صفاء', 'صمود',
    'حليم', 'حمدان', 'حمدي', 'زبير', 'زهير', 'ساطي', 'سامر', 'سراج', 'سفيان', 'شهاب',
    'ضحى', 'ضياء', 'طيبة', 'ظبية', 'عالية', 'عفاف', 'علياء', 'عنود', 'عهود', 'غدير',
    'صبري', 'صقر', 'صلاح', 'طاهر', 'طلعت', 'عابدين', 'عبود', 'عجاج', 'عفيف', 'عقيل',
    'غرام', 'غفران', 'فاتن', 'فادية', 'فايزة', 'فرح', 'فردوس', 'فريدة', 'فلك', 'فوزية',
    'فاروق', 'فتحي', 'فخري', 'فضل', 'فطين', 'قدري', 'كاسر', 'كنعان', 'كمال', 'مخلص',
    'قمر', 'كاميليا', 'كوثر', 'لبنى', 'ليان', 'لينا', 'مادلين', 'ماجدة', 'ماريا', 'ميساء',
    'محفوظ', 'مدين', 'مشير', 'معروف', 'معتز', 'مقداد', 'مكرم', 'منذر', 'منير', 'مهدي',
    'ملاك', 'ملك', 'منار', 'منال', 'مها', 'ميسون', 'ميرفت', 'ناجية', 'نادية', 'نادرة',
    'نصر', 'نضال', 'نظير', 'نوري', 'هايل', 'وجدي', 'وجيه', 'يزيد', 'يعقوب', 'وهيب',
    'نجمة', 'نجود', 'نداء', 'ندى', 'نرجس', 'نسيم', 'نعمة', 'نهاد', 'نهلة', 'نوارة',
    'أصيل', 'براء', 'تيم', 'جاد', 'حارث', 'خاطر', 'داني', 'دانيال', 'راغب', 'رامز',
    'نوف', 'هاجر', 'هديل', 'هنادي', 'هبة', 'هيام', 'وداد', 'ود', 'وسن', 'وصال',
    'زاهد', 'ساري', 'سالم', 'ساهر', 'سطام', 'سليم', 'سمير', 'سهيل', 'سيف', 'اصيل',
    'ورد', 'يمنى', 'يسرى', 'يمنى', 'ياقوت', 'يولاندا', 'امل', 'اميرة', 'ايمان', 'بثينة',
    'شادن', 'شامل', 'شعيب', 'صخر', 'صدام', 'صفا', 'ضاحي', 'ضرغام', 'طرفة', 'ظافر',
    'حورية', 'حياة', 'خولة', 'دارين', 'ريماس', 'زلفى', 'سارة', 'شيخة', 'صبحة', 'عذاري',
    'عامر', 'عبيدة', 'عتبة', 'عروة', 'عساف', 'عطية', 'عكاشة', 'عمير', 'عواد', 'عوض',
    'فجر', 'فدوة', 'فلك', 'أصيل', 'أيمن', 'أيهم', 'باسل', 'بشار', 'بكر', 'جبر',
    'جمان', 'حنين', 'ختام', 'دانية', 'رؤى', 'رغدة', 'رميساء', 'زينة', 'سجود', 'سدن',
    'جراح', 'جهينة', 'حاتم', 'حارثة', 'حسان', 'حسين', 'حيان', 'خزيمة', 'خشيش', 'داغر',
    'سما', 'سهر', 'شذى', 'صابرين', 'ضحى', 'طيف', 'عائشة', 'غلا', 'فدوى', 'قطر',
    'راجي', 'رداد', 'رزين', 'رضوان', 'رمزي', 'زهير', 'ساجر', 'سعدون', 'سنان', 'سيد',
    'الندى', 'لارا', 'لميس', 'لولوه', 'مجد', 'محاسن', 'مرح', 'مزن', 'مشاعل', 'ميعاد',
    'شهاب', 'شوقي', 'صايل', 'ضاري', 'عبيدة', 'عجيل', 'عليان', 'عمرو', 'غازي', 'فراس',
    'ميس', 'ميثاء', 'نغم', 'نها', 'نوران', 'نوف', 'نوني', 'هيفاء', 'وجد', 'وعد',
    'أبان', 'أبي', 'أجود', 'أحنف', 'أدهم', 'أركان', 'أزد', 'أسعد', 'أشجع', 'أشهب',
    'أغاريد', 'ألحان', 'ألطاف', 'أماني', 'أمنية', 'أميرة', 'أنغام', 'أيسر', 'إيثار', 'إيلاف',
    'أصيل', 'أكثم', 'ألماس', 'أيسر', 'إياس', 'إيهاب', 'بادي', 'بارق', 'باهي', 'بتال',
    'ابتسام', 'اعتدال', 'امتنان', 'انشراح', 'بدرية', ' بدور', 'برلنتي', 'بلسم', 'بنان', 'بنفسج',
    'بجاد', 'بدران', 'برجس', 'بركات', 'بشير', 'بطرس', 'بلال', 'بليغ', 'بهاء', 'بهيج',
    'بهجة', 'بوران', 'بيلسان', 'تالة', 'ترانيم', 'ترتيل', 'تسامح', 'تيسير', 'ثراء', 'ثريا',
    'تائب', 'تاجر', 'تالد', 'تالي', 'توفيق', 'تيمور', 'ثابت', 'ثاقب', 'ثروان', 'ثعلبة',
    'جلنار', 'جلوريا', 'جمانة', 'جمالات', 'جنات', 'جنين', 'جهينة', 'جوري', 'جيدا', 'جيلان',
    'جابر', 'جاد', 'جارالله', 'جبر', 'جراح', 'جرير', 'جساس', 'جلال', 'جليل', 'جميل',
    'حسيبة', 'حصة', 'حفيظة', 'حكيمة', 'حميدة', 'حنان', 'حواء', 'حور', 'حورية', 'حياة',
    'جواد', 'جود', 'جون', 'جهينة', 'جياد', 'حامد', 'حباب', 'حذيفة', 'حربي', 'حريث',
    'خديجة', 'خزنة', 'خصيبة', 'خضراء', 'خلود', 'خنساء', 'خيرة', 'خيرية', 'داليا', 'دانية',
    'حسام', 'حسن', 'حسيب', 'حسنين', 'حشمت', 'حطان', 'حكمت', 'حكيم', 'حليم', 'حماد',
    'دانية', 'دجانة', 'دجى', 'دلال', 'دليلة', 'دهماء', 'دوار', 'ديمة', 'دينا', 'ديانا',
    'حمد', 'حمدي', 'حمزة', 'حمود', 'حميد', 'حنان', 'حنبل', 'حنيفة', 'حيدر', 'حيان',
    'رابعة', 'رابية', 'راجحة', 'راغدة', 'رافدة', 'راما', 'رامية', 'رانيا', 'رانية', 'راوية',
    'خالد', 'خاطر', 'خشان', 'خشرم', 'خضر', 'خطاب', 'خلدون', 'خليفة', 'خليل', 'خميس',
    'رباب', 'ربى', 'رحمة', 'رحيق', 'رشا', 'رضية', 'رنا', 'رنيم', 'رواء', 'روان',
    'خويلد', 'خيرالله', 'خيري', 'داغر', 'داغر', 'داني', 'دانيال', 'داهش', 'داوود', 'دحام',
    'ريف', 'ريتال', 'ريتان', 'ريماس', 'رينا', 'ريهام', 'زبيدة', 'زكية', 'زمردة', 'زهراء',
    'درويش', 'دري', 'دليم', 'دهام', 'دياب', 'ديسم', 'دينار', 'ذكوان', 'ذكي', 'ذو',
    'سعاد', 'سعدية', 'سلطانة', 'سماهر', 'سمراء', 'سناء', 'سنية', 'سهيلة', 'سيرين', 'شكرية',
    'الفقار', 'رأفت', 'رائد', 'رئبال', 'رابح', 'راتب', 'راجح', 'راغب', 'راكان', 'رميح',
    'شادية', 'شهرزاد', 'شوق', 'شيماء', 'صافيناز', 'عزة', 'عزيزة', 'عصمت', 'عفاف', 'عنايات',
    'رشدي', 'رشوان', 'رشيد', 'رضا', 'رضوان', 'رفعت', 'رفيق', 'رمضان', 'رمزي', 'رياض',
    'غالية', 'فائزة', 'فاطمة', 'فدوى', 'فوزية', 'كريمة', 'كوكب', 'لمياء', 'ليلى', 'مايسة',
    'زغلول', 'زكريا', 'زكي', 'زهدي', 'زهير', 'زياد', 'زيد', 'زيدان', 'زين', 'زين',
    'محاسن', 'مديحة', 'ملك', 'منصورة', 'منى', 'نادية', 'ناهد', 'نبيلة', 'نجاة', 'نجلاء',
    'العابدين', 'سائد', 'ساتر', 'ساجد', 'ساري', 'سالم', 'سامح', 'ساهر', 'سجيع', 'سحاب',
    'نجوى', 'نزهة', 'نعيمة', 'نوال', 'نور', 'هانم', 'هادية', 'هالة', 'هند', 'هويدا',
    'سديد', 'سعد', 'سعدون', 'سعود', 'سعيد', 'سفيان', 'سلام', 'سلامة', 'سلطان', 'سلمان'
  ];

  private englishNames: string[] = [
    'James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda', 'William', 'Elizabeth',
    'David', 'Barbara', 'Richard', 'Susan', 'Joseph', 'Jessica', 'Thomas', 'Sarah', 'Charles', 'Karen',
    'Christopher', 'Nancy', 'Daniel', 'Lisa', 'Matthew', 'Betty', 'Anthony', 'Margaret', 'Mark', 'Sandra',
    'Donald', 'Ashley', 'Steven', 'Kimberly', 'Paul', 'Emily', 'Andrew', 'Donna', 'Joshua', 'Michelle',
    'Kevin', 'Dorothy', 'Brian', 'Carol', 'George', 'Amanda', 'Edward', 'Melissa', 'Ronald', 'Deborah',
    'Timothy', 'Stephanie', 'Jason', 'Rebecca', 'Jeffrey', 'Sharon', 'Ryan', 'Laura', 'Jacob', 'Cynthia',
    'Gary', 'Kathleen', 'Nicholas', 'Amy', 'Eric', 'Shirley', 'Jonathan', 'Angela', 'Stephen', 'Helen',
    'Larry', 'Anna', 'Justin', 'Brenda', 'Scott', 'Pamela', 'Brandon', 'Nicole', 'Benjamin', 'Emma',
    'Samuel', 'Samantha', 'Gregory', 'Katherine', 'Frank', 'Christine', 'Alexander', 'Debra', 'Raymond', 'Rachel',
    'Patrick', 'Catherine', 'Jack', 'Carolyn', 'Dennis', 'Janet', 'Jerry', 'Ruth', 'Tyler', 'Maria',
    'Aaron', 'Heather', 'Jose', 'Diane', 'Adam', 'Virginia', 'Henry', 'Julie', 'Nathan', 'Joyce',
    'Douglas', 'Victoria', 'Zachary', 'Olivia', 'Peter', 'Kelly', 'Kyle', 'Christina', 'Walter', 'Lauren',
    'Ethan', 'Joan', 'Jeremy', 'Evelyn', 'Harold', 'Judith', 'Keith', 'Megan', 'Christian', 'Cheryl',
    'Roger', 'Andrea', 'Noah', 'Hannah', 'Gerald', 'Martha', 'Carl', 'Jacqueline', 'Terry', 'Frances',
    'Sean', 'Gloria', 'Austin', 'Ann', 'Arthur', 'Teresa', 'Lawrence', 'Kathryn', 'Jesse', 'Sara',
    'Dylan', 'Janice', 'Bryan', 'Jean', 'Joe', 'Alice', 'Jordan', 'Madison', 'Billy', 'Doris',
    'Bruce', 'Mary', 'Gabriel', 'Julia', 'Logan', 'Grace', 'Albert', 'Judy', 'Willie', 'Abigail',
    'Alan', 'Marie', 'Juan', 'Denise', 'Wayne', 'Beverly', 'Elijah', 'Amber', 'Randy', 'Theresa',
    'Roy', 'Sophia', 'Vincent', 'Diana', 'Ralph', 'Brittany', 'Eugene', 'Natalie', 'Russell', 'Isabella',
    'Bobby', 'Charlotte', 'Mason', 'Rose', 'Philip', 'Alexis', 'Louis', 'Kayla', 'Liam', 'Lori',
    'Jayden', 'Ava', 'Caleb', 'Tiffany', 'Dylan', 'Chloe', 'Landon', 'Joan', 'Isaac', 'Evelyn',
    'Owen', 'April', 'Noah', 'Mia', 'Jackson', 'Lily', 'Aiden', 'Zoe', 'Lucas', 'Stella',
    'Leo', 'Penelope', 'Carter', 'Ruby', 'Ezra', 'Harper', 'Miles', 'Eleanor', 'Wyatt', 'Hazel',
    'Julian', 'Nora', 'Levi', 'Scarlett', 'Aaron', 'Madison', 'Eli', 'Riley', 'Connor', 'Aria',
    'Evan', 'Layla', 'Luke', 'Zoey', 'Jaxon', 'Paisley', 'Gavin', 'Ellie', 'Brayden', 'Claire',
    'Colton', 'Skylar', 'Grayson', 'Violet', 'Ryder', 'Savannah', 'Declan', 'Aubrey', 'Axel', 'Bella',
    'Kai', 'Aurora', 'Xavier', 'Lucy', 'Bentley', 'Anna', 'Asher', 'Samantha', 'Silas', 'Caroline',
    'Jason', 'Genesis', 'Josiah', 'Aaliyah', 'Mateo', 'Kennedy', 'Camden', 'Kinsley', 'Robert', 'Allison',
    'Ashton', 'Maya', 'Brody', 'Sarah', 'Micah', 'Madelyn', 'Ryker', 'Adalyn', 'Ian', 'Alexa',
    'Tristan', 'Ariana', 'Cole', 'Elena', 'Austin', 'Gabriella', 'Colin', 'Naomi', 'Dominic', 'Alice',
    'Lincoln', 'Sadie', 'Chase', 'Hailey', 'Kevin', 'Eva', 'Ayden', 'Emilia', 'Cooper', 'Autumn',
    'Hudson', 'Quinn', 'Carson', 'Nevaeh', 'Blake', 'Piper', 'Jaxson', 'Serenity', 'Easton', 'Lydia',
    'Parker', 'Peyton', 'Roman', 'Ruby', 'Damian', 'Taylor', 'Elias', 'Lillian', 'Harrison', 'Clara',
    'Zion', 'Madeline', 'Leonardo', 'Josephine', 'Santiago', 'Nicole', 'Alex', 'Reagan', 'Max', 'Vivian',
    'Everett', 'Kaylee', 'Ivan', 'Sophie', 'Kingston', 'Mackenzie', 'Jesus', 'Willow', 'Brantley', 'Juliette',
    'Abel', 'Paige', 'Emmett', 'Kimberly', 'Myles', 'Melody', 'Greyson', 'Julia', 'Jace', 'Cora',
    'Beau', 'Brielle', 'Weston', 'Gianna', 'Rowan', 'Eliana', 'Amir', 'Molly', 'Joel', 'Valeria',
    'Jonah', 'Trinity', 'Calvin', 'Daniela', 'Finn', 'Arya', 'Giovanni', 'Athena', 'Kaiden', 'Maria',
    'Diego', 'Eliza', 'Adrian', 'Raelynn', 'Elliot', 'Adeline', 'Milo', 'Isla', 'Emmanuel', 'Valerie',
    'Oscar', 'Andrea', 'Theodore', 'Sarah', 'Wyatt', 'Laila', 'Julian', 'Esther', 'Levi', 'Jasmine',
    'Luca', 'Rose', 'David', 'Annabelle', 'Daniel', 'Alexandra', 'Josiah', 'Rebecca', 'Michael', 'Mary',
    'Gabriel', 'Amy', 'Anthony', 'Faith', 'Matthew', 'Catherine', 'Angel', 'Angelina', 'Christopher', 'Isabelle',
    'Andrew', 'Payton', 'Joshua', 'Valentina', 'Joseph', 'Destiny', 'Nicholas', 'Vanessa', 'Jacob', 'Juliana',
    'Samuel', 'Morgan', 'John', 'Summer', 'Ryan', 'Melanie', 'Tyler', 'Jocelyn', 'Nathan', 'Gabrielle',
    'Jonathan', 'Bailey', 'Christian', 'Brooke', 'Brandon', 'Sydney', 'Benjamin', 'Paige', 'Justin', 'Alexa',
    'William', 'Kylie', 'James', 'Rachel', 'Caleb', 'Makayla', 'Alexander', 'Caroline', 'Zachary', 'Khloe',
    'Robert', 'Arianna', 'Kevin', 'Addison', 'Dylan', 'Peyton', 'Thomas', 'Aubree', 'Brian', 'Bella',
    'Jason', 'Aaliyah', 'Ethan', 'Layla', 'David', 'Taylor', 'Aaron', 'Mya', 'Eric', 'Kaitlyn',
    'Adam', 'Evelyn', 'Henry', 'Kayla', 'Jose', 'Alexis', 'Sean', 'Jordyn', 'Mark', 'Riley',
    'Walter', 'Genesis', 'Arthur', 'Serenity', 'Patrick', 'Nevaeh', 'Carl', 'Kennedy', 'George', 'Autumn',
    'Jerry', 'Quinn', 'Juan', 'Ariana', 'Larry', 'Lydia', 'Frank', 'Naomi', 'Dennis', 'Piper',
    'Edward', 'Madelyn', 'Paul', 'Ruby', 'Scott', 'Sadie', 'Stephen', 'Willow', 'Gregory', 'Clara',
    'Raymond', 'Josephine', 'Gary', 'Eliana', 'Peter', 'Cora', 'Timothy', 'Vivian', 'Ronald', 'Juliette',
    'Bruce', 'Isabelle', 'Daniel', 'Maria', 'Russell', 'Valentina', 'Roy', 'Destiny', 'Philip', 'Juliana',
    'Vincent', 'Morgan', 'Louis', 'Summer', 'Bobby', 'Melanie', 'Ralph', 'Jocelyn', 'Eugene', 'Gabrielle',
    'Willie', 'Bailey', 'Albert', 'Brooke', 'Billy', 'Sydney', 'Alan', 'Paige', 'Randy', 'Alexa',
    'Wayne', 'Kylie', 'Roger', 'Rachel', 'Harold', 'Makayla', 'Terry', 'Caroline', 'Gerald', 'Khloe',
    'Keith', 'Arianna', 'Joe', 'Addison', 'Lawrence', 'Peyton', 'Jesse', 'Aubree', 'Arthur', 'Bella',
    'Austin', 'Aaliyah', 'Sean', 'Layla', 'Christian', 'Taylor', 'Noah', 'Mya', 'Jeremy', 'Kaitlyn',
    'Walter', 'Evelyn', 'Kyle', 'Kayla', 'Peter', 'Alexis', 'Douglas', 'Jordyn', 'Henry', 'Riley',
    'Zachary', 'Genesis', 'Adam', 'Serenity', 'Jose', 'Nevaeh', 'Aaron', 'Kennedy', 'Tyler', 'Autumn',
    'Jerry', 'Quinn', 'Dennis', 'Ariana', 'Jack', 'Lydia', 'Patrick', 'Naomi', 'Raymond', 'Piper',
    'Gregory', 'Madelyn', 'Scott', 'Ruby', 'Stephen', 'Sadie', 'Paul', 'Willow', 'Edward', 'Clara',
    'Frank', 'Josephine', 'Larry', 'Eliana', 'Juan', 'Cora', 'Carl', 'Vivian', 'George', 'Juliette',
    'Brian', 'Isabelle', 'Thomas', 'Maria', 'Dylan', 'Valentina', 'Kevin', 'Destiny', 'Robert', 'Juliana',
    'Alexander', 'Morgan', 'Caleb', 'Summer', 'James', 'Melanie', 'William', 'Jocelyn', 'Justin', 'Gabrielle',
    'Benjamin', 'Bailey', 'Brandon', 'Brooke', 'Christian', 'Sydney', 'Jonathan', 'Paige', 'Nathan', 'Alexa',
    'Tyler', 'Kylie', 'Ryan', 'Rachel', 'John', 'Makayla', 'Samuel', 'Caroline', 'Jacob', 'Khloe',
    'Nicholas', 'Arianna', 'Joseph', 'Addison', 'Joshua', 'Peyton', 'Andrew', 'Aubree', 'Christopher', 'Bella',
    'Angel', 'Aaliyah', 'Matthew', 'Layla', 'Anthony', 'Taylor', 'David', 'Mya', 'Michael', 'Kaitlyn',
    'William', 'Evelyn', 'Richard', 'Kayla', 'Joseph', 'Alexis', 'Charles', 'Jordyn', 'Thomas', 'Riley',
    'Christopher', 'Genesis', 'Daniel', 'Serenity', 'Matthew', 'Nevaeh', 'Anthony', 'Kennedy', 'Donald', 'Autumn',
    'Mark', 'Quinn', 'Paul', 'Ariana', 'Steven', 'Lydia', 'Andrew', 'Naomi', 'Kevin', 'Piper',
    'Joshua', 'Madelyn', 'Kenneth', 'Ruby', 'Brian', 'Sadie', 'George', 'Willow', 'Edward', 'Clara',
    'Ronald', 'Josephine', 'Timothy', 'Eliana', 'Jason', 'Cora', 'Jeffrey', 'Vivian', 'Frank', 'Juliette',
    'Scott', 'Isabelle', 'Eric', 'Maria', 'Stephen', 'Valentina', 'Larry', 'Destiny', 'Jacob', 'Juliana',
    'Gary', 'Morgan', 'Nicholas', 'Summer', 'Raymond', 'Melanie', 'Gregory', 'Jocelyn', 'Ryan', 'Gabrielle',
    'Jerry', 'Bailey', 'Dennis', 'Brooke', 'Walter', 'Sydney', 'Patrick', 'Paige', 'Peter', 'Alexa',
    'Harold', 'Kylie', 'Douglas', 'Rachel', 'Henry', 'Makayla', 'Carl', 'Caroline', 'Arthur', 'Khloe',
    'Joe', 'Arianna', 'Roger', 'Addison', 'Juan', 'Peyton', 'Jack', 'Aubree', 'Terry', 'Bella',
    'Lawrence', 'Aaliyah', 'Austin', 'Layla', 'Billy', 'Taylor', 'Jesse', 'Mya', 'Sean', 'Kaitlyn',
    'Bruce', 'Evelyn', 'Albert', 'Kayla', 'Willie', 'Alexis', 'Alan', 'Jordyn', 'Ralph', 'Riley',
    'Randy', 'Genesis', 'Eugene', 'Serenity', 'Bobby', 'Nevaeh', 'Vincent', 'Kennedy', 'Louis', 'Autumn'
  ];

  private arabicWords: string[] = [
    'احبك', 'اعشقك', 'اهواك', 'حبيبي', 'حبيبتي', 'قلبي', 'عمري', 'روحي', 'جميل', 'رائع',
    'مرحبا', 'شكرا', 'السلام', 'عليكم', 'صباح', 'الخير', 'مساء', 'النور', 'كيف', 'الحال',
    'الحمدلله', 'ماشاءالله', 'سبحان', 'الله', 'اكبر', 'إنترنت', 'موقع', 'تطبيق', 'صديق', 'أسطورة',
    'أنا', 'أنت', 'هو', 'هي', 'نحن', 'هم', 'هن', 'هذا', 'هذه', 'ذلك',
    'كبير', 'صغير', 'طويل', 'قصير', 'جديد', 'قديم', 'جيد', 'سيء', 'سريع', 'بطيء',
    'بيت', 'سيارة', 'كتاب', 'قلم', 'مدرسة', 'جامعة', 'طالب', 'معلم', 'طبيب', 'مهندس',
    'ماء', 'طعام', 'هواء', 'نار', 'أرض', 'سماء', 'شمس', 'قمر', 'نجم', 'ليل',
    'نهار', 'يوم', 'أسبوع', 'شهر', 'سنة', 'وقت', 'ساعة', 'دقيقة', 'ثانية', 'لحظة',
    'أبيض', 'أسود', 'أحمر', 'أخضر', 'أزرق', 'أصفر', 'برتقالي', 'بنفسجي', 'وردي', 'بني',
    'واحد', 'اثنان', 'ثلاثة', 'أربعة', 'خمسة', 'ستة', 'سبعة', 'ثمانية', 'تسعة', 'عشرة',
    'عائلة', 'أب', 'أم', 'أخ', 'أخت', 'ابن', 'ابنة', 'جد', 'جدة', 'صديقة',
    'نعم', 'لا', 'ربما', 'أكيد', 'طبعا', 'ممكن', 'مستحيل', 'دائما', 'أبدا', 'أحيانا',
    'فوق', 'تحت', 'يمين', 'يسار', 'أمام', 'خلف', 'داخل', 'خارج', 'بين', 'حول',
    'ذهب', 'فضة', 'ألماس', 'لؤلؤ', 'حديد', 'نحاس', 'خشب', 'زجاج', 'بلاستيك', 'ورق',
    'يضحك', 'يبكي', 'يأكل', 'يشرب', 'ينام', 'يستيقظ', 'يعمل', 'يدرس', 'يلعب', 'يمشي',
    'يجري', 'يقفز', 'يتكلم', 'يسمع', 'يرى', 'يقرأ', 'يكتب', 'يفكر', 'يحلم', 'يسافر',
    'سعيد', 'حزين', 'غاضب', 'خائف', 'مندهش', 'متحمس', 'قلق', 'مرتاح', 'متعب', 'نشيط',
    'حر', 'برد', 'مطر', 'ثلج', 'ريح', 'عاصفة', 'ضباب', 'غيوم', 'صحو', 'مشمس',
    'حلو', 'مر', 'حامض', 'مالح', 'حار', 'بارد', 'ساخن', 'دافئ', 'رطب', 'جاف',
    'ذكي', 'غبي', 'شجاع', 'جبان', 'كريم', 'بخيل', 'صادق', 'كاذب', 'أمين', 'خائن',
    'قوي', 'ضعيف', 'غني', 'فقير', 'نظيف', 'متسخ', 'سهل', 'صعب', 'مهم', 'تافه',
    'عين', 'أذن', 'أنف', 'فم', 'لسان', 'يد', 'رجل', 'رأس', 'شعر', 'وجه',
    'صيف', 'شتاء', 'ربيع', 'خريف', 'فصل', 'طقس', 'حرارة', 'برودة', 'رطوبة', 'جفاف',
    'دولة', 'مدينة', 'قرية', 'شارع', 'بناية', 'شقة', 'غرفة', 'مطبخ', 'حمام', 'حديقة',
    'حيوان', 'طائر', 'سمكة', 'قطة', 'كلب', 'أسد', 'فيل', 'حصان', 'بقرة', 'خروف',
    'شجرة', 'زهرة', 'نبات', 'عشب', 'فاكهة', 'خضروات', 'تفاح', 'موز', 'برتقال', 'عنب',
    'بحر', 'نهر', 'بحيرة', 'جبل', 'سهل', 'وادي', 'صحراء', 'غابة', 'جزيرة', 'شاطئ',
    'صلاة', 'صيام', 'زكاة', 'حج', 'مسجد', 'قرآن', 'إسلام', 'إيمان', 'جنة', 'نار',
    'حرب', 'سلام', 'حب', 'كره', 'صداقة', 'عداوة', 'زواج', 'طلاق', 'حياة', 'موت',
    'علم', 'جهل', 'فن', 'أدب', 'شعر', 'موسيقى', 'رسم', 'تاريخ', 'جغرافيا', 'رياضيات',
    'كمبيوتر', 'هاتف', 'تلفاز', 'راديو', 'فيلم', 'مسلسل', 'أغنية', 'لعبة', 'رياضة', 'كرة',
    'قدم', 'سلة', 'طائرة', 'سباحة', 'جري', 'كفو', 'بوت', 'نوب', 'جلد', 'لايك',
    'متابعة', 'تعليق', 'هاشتاق', 'ترند', 'أونلاين', 'حساب', 'ملف', 'شخصي', 'صورة', 'فيديو',
    'رسالة', 'دردشة', 'مجموعة', 'منشور', 'قصة', 'بث', 'مباشر', 'تحدي', 'فلتر', 'ميمز',
    'بسم', 'الرحمن', 'الرحيم', 'استغفر', 'سبحانك', 'اللهم', 'وبحمدك', 'تبارك', 'اسمك', 'وتعالى',
    'جدك', 'ولا', 'إله', 'غيرك', 'لبيك', 'وسعديك', 'والخير', 'كله', 'في', 'يديك',
    'والشر', 'ليس', 'إليك', 'أستغفرك', 'وأتوب', 'إليك', 'أعوذ', 'بالله', 'من', 'الشيطان', 'الرجيم',
    'توكلت', 'على', 'لا', 'حول', 'ولا', 'قوة', 'إلا', 'بالله', 'العلي', 'العظيم', 'رضيت',
    'وبالإسلام', 'دينا', 'وبمحمد', 'صلى', 'عليه', 'وسلم', 'نبيا', 'ورسولا', 'حسبي', 'ونعم', 'الوكيل',
    'فنجان', 'قهوة', 'شاي', 'عصير', 'خبز', 'أرز', 'لحم', 'دجاج', 'خضار', 'سلطة',
    'حلم', 'أمل', 'هدف', 'نجاح', 'فشل', 'إصرار', 'عزيمة', 'طموح', 'مستقبل', 'ماضي',
    'أهلا', 'وسهلا', 'تشرفنا', 'مع', 'السلامة', 'إلى', 'اللقاء', 'عفوا', 'آسف', 'مبروك',
    'كل', 'عام', 'وأنتم', 'بخير', 'عيد', 'سعيد', 'مبارك', 'رمضان', 'كريم', 'بالتوفيق',
    'وطن', 'بلد', 'علم', 'نشيد', 'شعب', 'حرية', 'عدالة', 'مساواة', 'قانون', 'حكومة',
    'نور', 'ظلام', 'صوت', 'صمت', 'رائحة', 'طعم', 'ملمس', 'شعور', 'إحساس', 'عقل',
    'فكرة', 'رأي', 'حقيقة', 'خيال', 'سبب', 'نتيجة', 'بداية', 'نهاية', 'مشكلة', 'حل',
    'قلب', 'دماغ', 'روح', 'جسد', 'دم', 'عظم', 'جلد', 'عضلة', 'عصب', 'خلية',
    'سوق', 'متجر', 'بضاعة', 'مال', 'نقود', 'سعر', 'شراء', 'بيع', 'زبون', 'تاجر',
    'شركة', 'مصنع', 'مكتب', 'موظف', 'مدير', 'عمل', 'وظيفة', 'راتب', 'إجازة', 'تقاعد',
    'دنيا', 'آخرة', 'حساب', 'عقاب', 'ثواب', 'مغفرة', 'رحمة', 'رضا', 'دعاء', 'أجر',
    'صباح', 'مساء', 'ظهر', 'عصر', 'مغرب', 'عشاء', 'فجر', 'شروق', 'غروب', 'منتصف',
    'السبت', 'الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'اليوم', 'غدا', 'أمس',
    'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر',
    'نوفمبر', 'ديسمبر', 'محرم', 'صفر', 'ربيع', 'الأول', 'الآخر', 'جمادى', 'رجب', 'شعبان',
    'شوال', 'ذو', 'القعدة', 'الحجة', 'تقويم', 'ميلادي', 'هجري', 'تاريخ', 'زمن', 'عصر',
    'شمال', 'جنوب', 'شرق', 'غرب', 'اتجاه', 'مسافة', 'كيلومتر', 'ميل', 'متر', 'سنتيمتر',
    'مثال', 'نموذج', 'شكل', 'لون', 'حجم', 'وزن', 'طول', 'عرض', 'ارتفاع', 'عمق',
    'لغة', 'كلمة', 'جملة', 'حرف', 'رقم', 'نقطة', 'فاصلة', 'علامة', 'استفهام', 'تعجب',
    'زوج', 'زوجة', 'طفل', 'رجل', 'امرأة', 'شاب', 'فتاة', 'ولد', 'بنت', 'رضيع',
    'كهرباء', 'طاقة', 'ضوء', 'صوت', 'سرعة', 'قوة', 'جاذبية', 'حرارة', 'ذرة', 'جزيء',
    'سياسة', 'اقتصاد', 'مجتمع', 'ثقافة', 'تعليم', 'صحة', 'بيئة', 'تقنية', 'إعلام', 'قضاء',
    'ملك', 'رئيس', 'وزير', 'سفير', 'نائب', 'عضو', 'مواطن', 'لاجئ', 'مهاجر', 'غريب',
    'خطأ', 'صواب', 'صح', 'غلط', 'جريمة', 'عقوبة', 'سجن', 'براءة', 'ظلم', 'عدل',
    'خبر', 'مقالة', 'تقرير', 'إعلان', 'مجلة', 'جريدة', 'إذاعة', 'قناة', 'برنامج', 'مذيع',
    'شاعر', 'كاتب', 'روائي', 'فنان', 'رسام', 'ممثل', 'مخرج', 'منتج', 'ناقد', 'جمهور',
    'وحدة', 'ألم', 'فرح', 'ضحك', 'دموع', 'ابتسامة', 'خجل', 'فخر', 'غيرة', 'ندم',
    'وعد', 'عهد', 'سر', 'ثقة', 'أمانة', 'وفاء', 'إخلاص', 'تضحية', 'شوق', 'حنين',
    'ذكريات', 'لحظات', 'أيام', 'سنين', 'دهر', 'أبد', 'أزل', 'خلود', 'فناء', 'قدر',
    'مصيبة', 'نعمة', 'ابتلاء', 'صبر', 'شكر', 'يقين', 'أمل', 'رجاء', 'خوف', 'خشية',
    'سؤال', 'جواب', 'حوار', 'نقاش', 'جدال', 'صراخ', 'همس', 'لغو', 'ثرثرة', 'سكوت',
    'غياب', 'حضور', 'لقاء', 'فراق', 'وداع', 'عودة', 'رحيل', 'هجرة', 'استقرار', 'ترحال',
    'شهرة', 'مجد', 'عز', 'ذل', 'هوان', 'كرامة', 'شموخ', 'كبرياء', 'تواضع', 'بساطة',
    'حكمة', 'معرفة', 'فهم', 'وعي', 'إدراك', 'بديهة', 'فطنة', 'ذكاء', 'عبقرية', 'إبداع',
    'جمال', 'قبح', 'روعة', 'سحر', 'فتنة', 'جاذبية', 'أناقة', 'بشاعة', 'ترتيب', 'فوضى',
    'أصل', 'فرع', 'جذر', 'غصن', 'ورقة', 'برعم', 'ثمرة', 'بذرة', 'تربة', 'ساق',
    'غيوم', 'برق', 'رعد', 'قوس', 'قزح', 'زوبعة', 'إعصار', 'فيضان', 'جفاف', 'زلزال',
    'بركان', 'كهف', 'نفق', 'جسر', 'سد', 'قلعة', 'قصر', 'كوخ', 'خيمة', 'برج',
    'متحف', 'مكتبة', 'مسرح', 'سينما', 'ملعب', 'مسبح', 'نادي', 'مقهى', 'مطعم', 'فندق',
    'مستشفى', 'صيدلية', 'عيادة', 'مختبر', 'إسعاف', 'جراحة', 'علاج', 'دواء', 'مرض', 'شفاء',
    'شرطة', 'جيش', 'جندي', 'ضابط', 'سلاح', 'رصاصة', 'مدفع', 'دبابة', 'طائرة', 'سفينة',
    'محكمة', 'قاضي', 'محامي', 'متهم', 'شاهد', 'دليل', 'قضية', 'حكم', 'عدالة', 'قانون',
    'انتخابات', 'تصويت', 'مرشح', 'ناخب', 'حزب', 'برلمان', 'دستور', 'ديمقراطية', 'ديكتاتورية', 'ثورة',
    'حدود', 'جواز', 'سفر', 'تأشيرة', 'هوية', 'جنسية', 'إقامة', 'لجوء', 'تجسس', 'دفاع',
    'تجارة', 'صناعة', 'زراعة', 'سياحة', 'خدمات', 'استثمار', 'بورصة', 'بنك', 'عملة', 'ضريبة',
    'فقاعة', 'ظل', 'صدى', 'سراب', 'طيف', 'شبح', 'وهم', 'حقيقة', 'واقع', 'أسطورة',
    'معجزة', 'كرامة', 'سحر', 'شعوذة', 'تعويذة', 'تميمة', 'حسد', 'عين', 'جن', 'شياطين',
    'ملاك', 'نبي', 'رسول', 'ولي', 'صالح', 'شهيد', 'صديق', 'عابد', 'زاهد', 'تقي',
    'كفر', 'شرك', 'نفاق', 'بدعة', 'معصية', 'ذنب', 'خطيئة', 'توبة', 'استغفار', 'هداية',
    'عطر', 'بخور', 'مسك', 'عنبر', 'عود', 'ريحان', 'نعناع', 'ياسمين', 'ورد', 'فل',
    'شروق', 'غروب', 'فجر', 'ضحى', 'أصيل', 'غسق', 'دجى', 'سحر', 'زوال', 'عتمة',
    'بطل', 'شرير', 'ضحية', 'منقذ', 'مساعد', 'خصم', 'حليف', 'قائد', 'تابع', 'جاسوس',
    'قصيدة', 'رواية', 'مسرحية', 'مقالة', 'خطبة', 'حكاية', 'أغنية', 'لحن', 'إيقاع', 'قافية',
    'فلسفة', 'منطق', 'علم', 'نفس', 'اجتماع', 'أنثروبولوجيا', 'آثار', 'لغويات', 'بلاغة', 'نقد',
    'كيمياء', 'فيزياء', 'أحياء', 'فلك', 'جيولوجيا', 'هندسة', 'طب', 'صيدلة', 'تمريض', 'حاسوب'
  ];

  private englishWords: string[] = [
    'Love', 'Life', 'Happy', 'Sad', 'Cool', 'Epic', 'Game', 'Friend', 'Online', 'Welcome',
    'Time', 'Person', 'Year', 'Way', 'Day', 'Thing', 'Man', 'World', 'Hand', 'Part',
    'Child', 'Eye', 'Woman', 'Place', 'Work', 'Week', 'Case', 'Point', 'Government', 'Company',
    'Number', 'Group', 'Problem', 'Fact', 'Family', 'Story', 'System', 'Computer', 'Money', 'Music',
    'Art', 'War', 'History', 'Party', 'Result', 'Change', 'Morning', 'Reason', 'Research', 'Girl',
    'Guy', 'Moment', 'Air', 'Teacher', 'Force', 'Education', 'Food', 'Water', 'Home', 'Job',
    'Country', 'President', 'Book', 'School', 'Student', 'Room', 'Car', 'City', 'Community', 'Name',
    'Team', 'Minute', 'Idea', 'Kid', 'Body', 'Information', 'Back', 'Parent', 'Face', 'Others',
    'Level', 'Office', 'Door', 'Health', 'Person', 'Power', 'Law', 'War', 'God', 'End',
    'Word', 'Business', 'Issue', 'Side', 'Kind', 'Head', 'House', 'Service', 'Friend', 'Father',
    'Power', 'Hour', 'Game', 'Line', 'End', 'Member', 'Law', 'Car', 'City', 'Community',
    'Name', 'President', 'Team', 'Minute', 'Idea', 'Kid', 'Body', 'Information', 'Back', 'Parent',
    'Face', 'Others', 'Level', 'Office', 'Door', 'Health', 'Person', 'Art', 'War', 'History',
    'Party', 'Result', 'Change', 'Morning', 'Reason', 'Research', 'Girl', 'Guy', 'Moment', 'Air',
    'Teacher', 'Force', 'Education', 'Ability', 'Able', 'About', 'Above', 'Accept', 'According', 'Account',
    'Across', 'Act', 'Action', 'Activity', 'Actually', 'Add', 'Address', 'Administration', 'Admit', 'Adult',
    'Affect', 'After', 'Again', 'Against', 'Age', 'Agency', 'Agent', 'Ago', 'Agree', 'Agreement',
    'Ahead', 'Allow', 'Almost', 'Alone', 'Along', 'Already', 'Also', 'Although', 'Always', 'American',
    'Among', 'Amount', 'Analysis', 'And', 'Animal', 'Another', 'Answer', 'Any', 'Anyone', 'Anything',
    'Appear', 'Apply', 'Approach', 'Area', 'Argue', 'Arm', 'Around', 'Arrive', 'Article', 'Artist',
    'Ask', 'Assume', 'Attack', 'Attention', 'Attorney', 'Audience', 'Author', 'Authority', 'Available', 'Avoid',
    'Away', 'Baby', 'Ball', 'Bank', 'Bar', 'Base', 'Beat', 'Beautiful', 'Because', 'Become',
    'Bed', 'Before', 'Begin', 'Behavior', 'Behind', 'Believe', 'Benefit', 'Best', 'Better', 'Between',
    'Beyond', 'Big', 'Bill', 'Billion', 'Bit', 'Black', 'Blood', 'Blue', 'Board', 'Boat',
    'Book', 'Born', 'Both', 'Box', 'Boy', 'Break', 'Bring', 'Brother', 'Budget', 'Build',
    'Building', 'Burn', 'But', 'Buy', 'Call', 'Camera', 'Campaign', 'Can', 'Cancer', 'Candidate',
    'Capital', 'Card', 'Care', 'Career', 'Carry', 'Catch', 'Cause', 'Cell', 'Center', 'Central',
    'Century', 'Certain', 'Certainly', 'Chair', 'Challenge', 'Chance', 'Character', 'Charge', 'Check', 'Chief',
    'Choose', 'Choice', 'Church', 'Citizen', 'Claim', 'Class', 'Clear', 'Clearly', 'Close', 'Coach',
    'Cold', 'Collection', 'College', 'Color', 'Come', 'Commercial', 'Common', 'Compare', 'Condition', 'Conference',
    'Congress', 'Consider', 'Consumer', 'Contain', 'Continue', 'Control', 'Cost', 'Could', 'Council', 'Couple',
    'Course', 'Court', 'Cover', 'Create', 'Crime', 'Cultural', 'Culture', 'Cup', 'Current', 'Customer',
    'Cut', 'Dark', 'Data', 'Daughter', 'Deal', 'Death', 'Debate', 'Decade', 'Decide', 'Decision',
    'Deep', 'Defense', 'Degree', 'Democrat', 'Democratic', 'Describe', 'Design', 'Despite', 'Detail', 'Determine',
    'Develop', 'Development', 'Die', 'Difference', 'Different', 'Difficult', 'Dinner', 'Direction', 'Director', 'Discover',
    'Discuss', 'Discussion', 'Disease', 'Doctor', 'Dog', 'Dream', 'Drive', 'Drop', 'Drug', 'During',
    'Each', 'Early', 'East', 'Easy', 'Eat', 'Economic', 'Economy', 'Edge', 'Effect', 'Effort',
    'Eight', 'Either', 'Election', 'Else', 'Employee', 'Energy', 'Enjoy', 'Enough', 'Enter', 'Entire',
    'Environment', 'Environmental', 'Especially', 'Establish', 'Even', 'Evening', 'Event', 'Ever', 'Every', 'Everybody',
    'Everyone', 'Everything', 'Evidence', 'Exactly', 'Example', 'Executive', 'Exist', 'Expect', 'Experience', 'Expert',
    'Explain', 'Factor', 'Fail', 'Fall', 'Far', 'Farm', 'Fast', 'Fear', 'Federal', 'Feel',
    'Feeling', 'Few', 'Field', 'Fight', 'Figure', 'Fill', 'Film', 'Final', 'Finally', 'Financial',
    'Find', 'Fine', 'Finger', 'Finish', 'Fire', 'Firm', 'First', 'Fish', 'Five', 'Floor',
    'Fly', 'Focus', 'Follow', 'Foot', 'For', 'Foreign', 'Forget', 'Form', 'Former', 'Forward',
    'Four', 'Free', 'Friendship', 'From', 'Front', 'Full', 'Fund', 'Future', 'Garden', 'Gas',
    'General', 'Generation', 'Get', 'Give', 'Glass', 'Go', 'Goal', 'Good', 'Great', 'Green',
    'Ground', 'Grow', 'Growth', 'Guess', 'Gun', 'Hair', 'Half', 'Hand', 'Hang', 'Happen',
    'Hard', 'Have', 'He', 'Heart', 'Heat', 'Heavy', 'Help', 'Her', 'Here', 'Herself',
    'High', 'Him', 'Himself', 'His', 'Hold', 'Hope', 'Hospital', 'Hot', 'Hotel', 'However',
    'Huge', 'Human', 'Hundred', 'Husband', 'I', 'Ice', 'Imagine', 'Impact', 'Important', 'Improve',
    'In', 'Include', 'Including', 'Increase', 'Indeed', 'Indicate', 'Individual', 'Industry', 'Inside', 'Instead',
    'Institution', 'Interest', 'Interesting', 'International', 'Interview', 'Into', 'Investment', 'Involve', 'Is', 'Island',
    'It', 'Item', 'Its', 'Itself', 'Jesus', 'Join', 'Just', 'Keep', 'Key', 'Kill',
    'King', 'Kitchen', 'Know', 'Knowledge', 'Land', 'Language', 'Large', 'Last', 'Late', 'Later',
    'Laugh', 'Lay', 'Lead', 'Leader', 'Learn', 'Least', 'Leave', 'Left', 'Leg', 'Legal',
    'Less', 'Let', 'Letter', 'Lie', 'Light', 'Like', 'Likely', 'Listen', 'Little', 'Live',
    'Local', 'Long', 'Look', 'Lose', 'Loss', 'Lot', 'Low', 'Machine', 'Magazine', 'Main',
    'Maintain', 'Major', 'Majority', 'Make', 'Manage', 'Management', 'Manager', 'Many', 'Market', 'Marriage',
    'Material', 'Matter', 'May', 'Maybe', 'Me', 'Mean', 'Measure', 'Media', 'Medical', 'Meet',
    'Meeting', 'Mention', 'Message', 'Method', 'Middle', 'Might', 'Military', 'Million', 'Mind', 'Miss',
    'Mission', 'Model', 'Modern', 'Month', 'More', 'Most', 'Mother', 'Mouth', 'Move', 'Movement',
    'Movie', 'Mr', 'Mrs', 'Much', 'My', 'Myself', 'Nation', 'National', 'Natural', 'Nature',
    'Near', 'Nearly', 'Necessary', 'Need', 'Network', 'Never', 'New', 'News', 'Newspaper', 'Next',
    'Nice', 'Night', 'No', 'None', 'Nor', 'North', 'Not', 'Note', 'Nothing', 'Notice',
    'Now', 'N’t', 'Of', 'Off', 'Offer', 'Officer', 'Official', 'Often', 'Oh', 'Oil',
    'Ok', 'Old', 'On', 'Once', 'One', 'Only', 'Onto', 'Open', 'Operation', 'Opportunity',
    'Option', 'Or', 'Order', 'Organization', 'Other', 'Others', 'Our', 'Out', 'Outside', 'Over',
    'Own', 'Owner', 'Page', 'Pain', 'Painting', 'Paper', 'Parent', 'Part', 'Participant', 'Particular',
    'Particularly', 'Partner', 'Pass', 'Past', 'Patient', 'Pattern', 'Pay', 'Peace', 'People', 'Per',
    'Perform', 'Performance', 'Perhaps', 'Period', 'Personal', 'Phone', 'Physical', 'Pick', 'Picture', 'Piece',
    'Plan', 'Plant', 'Play', 'Player', 'PM', 'Police', 'Policy', 'Political', 'Politics', 'Poor',
    'Popular', 'Population', 'Position', 'Positive', 'Possible', 'Practice', 'Prepare', 'Present', 'President', 'Pressure',
    'Pretty', 'Prevent', 'Price', 'Private', 'Probably', 'Process', 'Produce', 'Product', 'Production', 'Professional',
    'Professor', 'Program', 'Project', 'Property', 'Protect', 'Prove', 'Provide', 'Public', 'Pull', 'Purpose',
    'Push', 'Put', 'Quality', 'Question', 'Quickly', 'Quite', 'Race', 'Radio', 'Raise', 'Range',
    'Rate', 'Rather', 'Reach', 'Read', 'Ready', 'Real', 'Reality', 'Realize', 'Really', 'Receive',
    'Recent', 'Recently', 'Recognize', 'Record', 'Red', 'Reduce', 'Reflect', 'Region', 'Relate', 'Relationship',
    'Religious', 'Remain', 'Remember', 'Remove', 'Report', 'Represent', 'Republican', 'Require', 'Resource', 'Respond',
    'Response', 'Responsibility', 'Rest', 'Return', 'Reveal', 'Rich', 'Right', 'Rise', 'Risk', 'Road',
    'Rock', 'Role', 'Run', 'Safe', 'Same', 'Save', 'Say', 'Scene', 'Science', 'Scientist',
    'Score', 'Sea', 'Season', 'Seat', 'Second', 'Section', 'Security', 'See', 'Seek', 'Seem',
    'Sell', 'Send', 'Senior', 'Sense', 'Series', 'Serious', 'Serve', 'Set', 'Seven', 'Several',
    'Sex', 'Sexual', 'Shake', 'Share', 'She', 'Shoot', 'Short', 'Shot', 'Should', 'Shoulder',
    'Show', 'Sign', 'Significant', 'Similar', 'Simple', 'Simply', 'Since', 'Sing', 'Single', 'Sister',
    'Sit', 'Site', 'Situation', 'Six', 'Size', 'Skill', 'Skin', 'Small', 'Smile', 'So',
    'Social', 'Society', 'Soldier', 'Some', 'Somebody', 'Someone', 'Something', 'Sometimes', 'Son', 'Song',
    'Soon', 'Sort', 'Sound', 'Source', 'South', 'Southern', 'Space', 'Speak', 'Special', 'Specific',
    'Speech', 'Spend', 'Sport', 'Spring', 'Staff', 'Stage', 'Stand', 'Standard', 'Star', 'Start',
    'State', 'Statement', 'Station', 'Stay', 'Step', 'Still', 'Stock', 'Stop', 'Store', 'Strategy',
    'Street', 'Strong', 'Structure', 'Study', 'Stuff', 'Style', 'Subject', 'Success', 'Successful', 'Such',
    'Suddenly', 'Suffer', 'Suggest', 'Summer', 'Support', 'Sure', 'Surface', 'Table', 'Take', 'Talk',
    'Tax', 'Teach', 'Technology', 'Television', 'Tell', 'Ten', 'Tend', 'Term', 'Test', 'Than',
    'Thank', 'That', 'The', 'Their', 'Them', 'Themselves', 'Then', 'Theory', 'There', 'These',
    'They', 'Thing', 'Think', 'Third', 'This', 'Those', 'Though', 'Thought', 'Thousand', 'Threat',
    'Three', 'Through', 'Throughout', 'Throw', 'Thus', 'Till', 'To', 'Today', 'Together', 'Tonight',
    'Too', 'Top', 'Total', 'Tough', 'Toward', 'Town', 'Trade', 'Traditional', 'Training', 'Travel',
    'Treat', 'Treatment', 'Tree', 'Trial', 'Trip', 'Trouble', 'True', 'Truth', 'Try', 'Turn',
    'TV', 'Two', 'Type', 'Under', 'Understand', 'Unit', 'Until', 'Up', 'Upon', 'Us',
    'Use', 'Usually', 'Value', 'Various', 'Very', 'Victim', 'View', 'Violence', 'Visit', 'Voice',
    'Vote', 'Wait', 'Walk', 'Wall', 'Want', 'Watch', 'Way', 'We', 'Weapon', 'Wear',
    'Weight', 'Well', 'West', 'Western', 'What', 'Whatever', 'When', 'Where', 'Whether', 'Which',
    'While', 'White', 'Who', 'Whole', 'Whom', 'Whose', 'Why', 'Wide', 'Wife', 'Will',
    'Win', 'Wind', 'Window', 'Wish', 'With', 'Within', 'Without', 'Wolf', 'Wonder', 'Wonderful',
    'Wood', 'Word', 'Work', 'Worker', 'Would', 'Wow', 'Write', 'Writer', 'Wrong', 'Yard',
    'Yeah', 'Yet', 'You', 'Young', 'Your', 'Yourself'
  ];

  getArabicNames(): string[] {
    return this.arabicNames.sort();
  }
  
  getEnglishNames(): string[] {
    return this.englishNames.sort();
  }

  getArabicWords(): string[] {
    return this.arabicWords.sort();
  }

  getEnglishWords(): string[] {
    return this.englishWords.sort();
  }

  private getRelatedItems(allItems: string[], currentItem: string, count: number): string[] {
    const filtered = allItems.filter(item => item !== currentItem);
    const shuffled = filtered.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
  }

  getRelatedNames(currentName: string, lang: 'ar' | 'en'): string[] {
    const sourceList = lang === 'ar' ? this.arabicNames : this.englishNames;
    return this.getRelatedItems(sourceList, currentName, 5);
  }

  getRelatedWords(currentWord: string, lang: 'ar' | 'en'): string[] {
    const sourceList = lang === 'ar' ? this.arabicWords : this.englishWords;
    return this.getRelatedItems(sourceList, currentWord, 5);
  }
}